### ISSUE TITLE
Add REST-API Documentation 

### ISSUE THREAD

**Issue by Shynixn** [lukasbindreiter/enternot-pi#14]
Please list up each endpoint in readme, swagger, whatever.

**Comment by lukasbindreiter** [comment]
Documentation is provided by the `docs/swagger.yaml` file. You can view it using Swagger UI using [this link](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/lukasbindreiter/enternot-pi/master/docs/swagger.yaml)

Endpoints and their names may be open to change.
